- hosts: all
  tasks:
  - copy:
          dest: "/etc/yum.repos.d"
          src: "epel-modular.repo"
  - copy:
          dest: "/etc/yum.repos.d"
          src: "epel-playground.repo"
  - copy:
          dest: "/etc/yum.repos.d"
          src: "rpmfusion-free-updates.repo"
  - copy:
          dest: "/etc/yum.repos.d"
          src: "epel-testing.repo"
  - copy:
          dest: "/etc/yum.repos.d"
          src: "rpmfusion-free-updates-testing.repo"
          
   - copy:
          dest: "/etc/yum.repos.d"
          src: "epel-testing-modular.repo"
   - copy:
          dest: "/etc/yum.repos.d"
          src: "epel.repo"       
